-- 시간연차(시간 단위 휴가) 지원
-- - 1일 = 8시간 가정. 1시간 = 0.125일 → days 컬럼은 NUMERIC(6,3) 으로 확장.
-- - GW_LEAVE_REQ 에 START_AT / END_AT TIMESTAMP 추가하여 시각을 기록.

ALTER TABLE GW_LEAVE_REQ ALTER COLUMN DAYS SET DATA TYPE NUMERIC(6,3);
ALTER TABLE GW_LEAVE_REQ ADD COLUMN START_AT TIMESTAMP;
ALTER TABLE GW_LEAVE_REQ ADD COLUMN END_AT   TIMESTAMP;

ALTER TABLE GW_LEAVE_BALANCE ALTER COLUMN ANNUAL_GIVEN SET DATA TYPE NUMERIC(6,3);
ALTER TABLE GW_LEAVE_BALANCE ALTER COLUMN ANNUAL_USED  SET DATA TYPE NUMERIC(6,3);

-- 코드 등록
INSERT INTO GW_CODE (GROUP_CD, CODE_VAL, CODE_NM, SORT_NO)
VALUES ('LEAVE_TYPE','HOURLY','시간연차',5);
