-- 인사 정보 확장: 경력 / 학력 / 교육이수 / 상벌

-- ─────────────── 경력 (이전 회사 경력) ───────────────
CREATE TABLE GW_HR_CAREER (
    CAREER_ID    BIGSERIAL PRIMARY KEY,
    USER_ID      BIGINT NOT NULL,
    COMPANY_NM   VARCHAR(200) NOT NULL,
    POSITION_NM  VARCHAR(100),
    START_DT     DATE NOT NULL,
    END_DT       DATE,
    DESCRIPTION  VARCHAR(2000),
    CREATED_AT   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY   BIGINT
);
CREATE INDEX IX_GW_HR_CAREER_USER ON GW_HR_CAREER(USER_ID, START_DT DESC);

-- ─────────────── 학력 ───────────────
CREATE TABLE GW_HR_EDUCATION (
    EDU_ID         BIGSERIAL PRIMARY KEY,
    USER_ID        BIGINT NOT NULL,
    SCHOOL_NM      VARCHAR(200) NOT NULL,
    MAJOR          VARCHAR(100),
    DEGREE_CD      VARCHAR(20),            -- HIGHSCHOOL / ASSOCIATE / BACHELOR / MASTER / DOCTORATE
    EDU_STATUS_CD  VARCHAR(20) NOT NULL,   -- ENROLLED / GRADUATED / DROPPED
    ADMISSION_DT   DATE,
    GRADUATION_DT  DATE,
    CREATED_AT     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY     BIGINT
);
CREATE INDEX IX_GW_HR_EDU_USER ON GW_HR_EDUCATION(USER_ID, GRADUATION_DT DESC);

-- ─────────────── 교육이수 (사내·사외 교육) ───────────────
CREATE TABLE GW_HR_TRAINING (
    TRN_ID       BIGSERIAL PRIMARY KEY,
    USER_ID      BIGINT NOT NULL,
    COURSE_NM    VARCHAR(200) NOT NULL,
    PROVIDER_NM  VARCHAR(200),
    START_DT     DATE,
    END_DT       DATE,
    HOURS        NUMERIC(5,1),
    CERT_NO      VARCHAR(100),
    CREATED_AT   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY   BIGINT
);
CREATE INDEX IX_GW_HR_TRN_USER ON GW_HR_TRAINING(USER_ID, END_DT DESC);

-- ─────────────── 상벌 ───────────────
CREATE TABLE GW_HR_AWARD (
    AWARD_ID       BIGSERIAL PRIMARY KEY,
    USER_ID        BIGINT NOT NULL,
    AWARD_TYPE_CD  VARCHAR(20) NOT NULL,   -- AWARD / PUNISHMENT
    TITLE          VARCHAR(200) NOT NULL,
    OCCURRED_ON    DATE NOT NULL,
    ORGANIZATION   VARCHAR(200),
    REASON         VARCHAR(2000),
    CREATED_AT     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY     BIGINT
);
CREATE INDEX IX_GW_HR_AWARD_USER ON GW_HR_AWARD(USER_ID, OCCURRED_ON DESC);

-- ─────────────── 코드 시드 ───────────────
INSERT INTO GW_CODE_GROUP (GROUP_CD, GROUP_NM, DESCRIPTION) VALUES
 ('HR_DEGREE','학위',NULL),
 ('HR_EDU_STATUS','학적상태',NULL),
 ('HR_AWARD_TYPE','상벌 유형',NULL);

INSERT INTO GW_CODE (GROUP_CD, CODE_VAL, CODE_NM, SORT_NO) VALUES
 ('HR_DEGREE','HIGHSCHOOL','고졸',1),
 ('HR_DEGREE','ASSOCIATE','전문학사',2),
 ('HR_DEGREE','BACHELOR','학사',3),
 ('HR_DEGREE','MASTER','석사',4),
 ('HR_DEGREE','DOCTORATE','박사',5),
 ('HR_EDU_STATUS','ENROLLED','재학',1),
 ('HR_EDU_STATUS','GRADUATED','졸업',2),
 ('HR_EDU_STATUS','DROPPED','중퇴',3),
 ('HR_AWARD_TYPE','AWARD','포상',1),
 ('HR_AWARD_TYPE','PUNISHMENT','징계',2);
