-- 명시 ID 로 시드된 테이블의 IDENTITY 시퀀스를 시드 max + 여유 값으로 재설정.
-- V2 / V5 에서 `INSERT INTO ... (MENU_ID, ...) VALUES (1, ...)` 와 같이 PK 를
-- 직접 지정해 시드한 결과 BIGSERIAL/IDENTITY 의 다음 값이 1 로 남아 있어,
-- 운영 중 신규 row INSERT 시 PK 중복(DuplicateKeyException) 이 발생했다.
-- H2 와 PostgreSQL 모두 ALTER TABLE ... ALTER COLUMN ... RESTART WITH N 을 지원.

ALTER TABLE GW_TENANT   ALTER COLUMN TENANT_ID   RESTART WITH 1000;
ALTER TABLE GW_DEPT     ALTER COLUMN DEPT_ID     RESTART WITH 1000;
ALTER TABLE GW_POSITION ALTER COLUMN POSITION_ID RESTART WITH 1000;
ALTER TABLE GW_MENU     ALTER COLUMN MENU_ID     RESTART WITH 1000;
ALTER TABLE GW_ROOM     ALTER COLUMN ROOM_ID     RESTART WITH 1000;
