-- 데이터 표준화 — 코드값 시드 보강 + audit 컬럼 보강
--
-- 1) 컨트롤러/매퍼에서 사용 중이지만 GW_CODE 에 등록되지 않은 코드 그룹들을
--    공통코드 체계로 이관해 한글 라벨/JOIN 노출/관리 화면에서 일관 관리.
-- 2) audit 컬럼(UPDATED_*, DELETED_AT) 이 누락된 운영 테이블에 추가해
--    변경 이력 추적 가능하게 함.

-- ========== 1. 코드 그룹 / 코드값 시드 ==========

INSERT INTO GW_CODE_GROUP (GROUP_CD, GROUP_NM, DESCRIPTION) VALUES
 ('CAL_SCOPE','일정 공유 범위','PERSONAL/DEPT/COMPANY'),
 ('ASSET_STATUS','자산 상태','IN_STOCK/IN_USE/REPAIRING/DISPOSED'),
 ('VEHICLE_STATUS','차량 상태','AVAILABLE/IN_USE/MAINTENANCE/DISPOSED'),
 ('VEHICLE_RES_STATUS','차량 예약 상태','PENDING/APPROVED/IN_USE/COMPLETED/CANCELED'),
 ('INVOICE_DIRECTION','인보이스 방향','OUT(매출)/IN(매입)'),
 ('INVOICE_STATUS','인보이스 상태','DRAFT/ISSUED/PARTIALLY_PAID/PAID/OVERDUE/CANCELED'),
 ('EMP_CONTRACT_TYPE','근로계약 종류','REGULAR/FIXED_TERM/PART_TIME/TEMP/INTERN'),
 ('EMP_CONTRACT_STATUS','근로계약 상태','DRAFT/SENT/SIGNED/ACTIVE/TERMINATED'),
 ('SALARY_DIV_TYPE','급여 형태','MONTHLY/HOURLY/DAILY/ANNUAL'),
 ('PAYROLL_STATUS','급여 처리 상태','DRAFT/CONFIRMED/PAID/CANCELED'),
 ('BIZ_CONTRACT_STATUS','사업자계약 상태','DRAFT/ACTIVE/TERMINATED/EXPIRED'),
 ('LEAVE_REQ_STATUS','휴가 신청 상태','DRAFT/IN_PROGRESS/APPROVED/REJECTED/CANCELED');

INSERT INTO GW_CODE (GROUP_CD, CODE_VAL, CODE_NM, SORT_NO) VALUES
 ('CAL_SCOPE','PERSONAL','개인',1),
 ('CAL_SCOPE','DEPT','부서 공유',2),
 ('CAL_SCOPE','COMPANY','전사',3),

 ('ASSET_STATUS','IN_STOCK','사용가능',1),
 ('ASSET_STATUS','IN_USE','사용중',2),
 ('ASSET_STATUS','REPAIRING','수리중',3),
 ('ASSET_STATUS','DISPOSED','폐기',4),

 ('VEHICLE_STATUS','AVAILABLE','운행가능',1),
 ('VEHICLE_STATUS','IN_USE','운행중',2),
 ('VEHICLE_STATUS','MAINTENANCE','정비중',3),
 ('VEHICLE_STATUS','DISPOSED','폐차',4),

 ('VEHICLE_RES_STATUS','PENDING','대기',1),
 ('VEHICLE_RES_STATUS','APPROVED','승인',2),
 ('VEHICLE_RES_STATUS','IN_USE','사용중',3),
 ('VEHICLE_RES_STATUS','COMPLETED','반납완료',4),
 ('VEHICLE_RES_STATUS','CANCELED','취소',5),

 ('INVOICE_DIRECTION','OUT','매출',1),
 ('INVOICE_DIRECTION','IN','매입',2),

 ('INVOICE_STATUS','DRAFT','초안',1),
 ('INVOICE_STATUS','ISSUED','발행',2),
 ('INVOICE_STATUS','PARTIALLY_PAID','부분지급',3),
 ('INVOICE_STATUS','PAID','지급완료',4),
 ('INVOICE_STATUS','OVERDUE','연체',5),
 ('INVOICE_STATUS','CANCELED','취소',9),

 ('EMP_CONTRACT_TYPE','REGULAR','정규직',1),
 ('EMP_CONTRACT_TYPE','FIXED_TERM','기간제',2),
 ('EMP_CONTRACT_TYPE','PART_TIME','단시간',3),
 ('EMP_CONTRACT_TYPE','TEMP','시용',4),
 ('EMP_CONTRACT_TYPE','INTERN','인턴',5),

 ('EMP_CONTRACT_STATUS','DRAFT','초안',1),
 ('EMP_CONTRACT_STATUS','SENT','서명요청',2),
 ('EMP_CONTRACT_STATUS','SIGNED','서명완료',3),
 ('EMP_CONTRACT_STATUS','ACTIVE','유효',4),
 ('EMP_CONTRACT_STATUS','TERMINATED','해지',9),

 ('SALARY_DIV_TYPE','MONTHLY','월급제',1),
 ('SALARY_DIV_TYPE','HOURLY','시급제',2),
 ('SALARY_DIV_TYPE','DAILY','일급제',3),
 ('SALARY_DIV_TYPE','ANNUAL','연봉제',4),

 ('PAYROLL_STATUS','DRAFT','초안',1),
 ('PAYROLL_STATUS','CONFIRMED','확정',2),
 ('PAYROLL_STATUS','PAID','지급완료',3),
 ('PAYROLL_STATUS','CANCELED','취소',9),

 ('BIZ_CONTRACT_STATUS','DRAFT','초안',1),
 ('BIZ_CONTRACT_STATUS','ACTIVE','유효',2),
 ('BIZ_CONTRACT_STATUS','TERMINATED','해지',3),
 ('BIZ_CONTRACT_STATUS','EXPIRED','만료',4),

 ('LEAVE_REQ_STATUS','DRAFT','임시저장',1),
 ('LEAVE_REQ_STATUS','IN_PROGRESS','결재중',2),
 ('LEAVE_REQ_STATUS','APPROVED','승인',3),
 ('LEAVE_REQ_STATUS','REJECTED','반려',4),
 ('LEAVE_REQ_STATUS','CANCELED','취소',5);

-- ========== 2. Audit 컬럼 보강 ==========

-- GW_PAYMENT: CREATED_AT 만 → UPDATED_*, DELETED_AT 추가
ALTER TABLE GW_PAYMENT ADD COLUMN IF NOT EXISTS CREATED_BY BIGINT;
ALTER TABLE GW_PAYMENT ADD COLUMN IF NOT EXISTS UPDATED_AT TIMESTAMP;
ALTER TABLE GW_PAYMENT ADD COLUMN IF NOT EXISTS UPDATED_BY BIGINT;
ALTER TABLE GW_PAYMENT ADD COLUMN IF NOT EXISTS DELETED_AT TIMESTAMP;

-- GW_ROOM (회의실 마스터) : 변경 이력 추적용
ALTER TABLE GW_ROOM ADD COLUMN IF NOT EXISTS CREATED_BY BIGINT;
ALTER TABLE GW_ROOM ADD COLUMN IF NOT EXISTS UPDATED_AT TIMESTAMP;
ALTER TABLE GW_ROOM ADD COLUMN IF NOT EXISTS UPDATED_BY BIGINT;

-- GW_ROOM_RES (예약) : 변경자 추적
ALTER TABLE GW_ROOM_RES ADD COLUMN IF NOT EXISTS CREATED_BY BIGINT;
ALTER TABLE GW_ROOM_RES ADD COLUMN IF NOT EXISTS UPDATED_AT TIMESTAMP;
ALTER TABLE GW_ROOM_RES ADD COLUMN IF NOT EXISTS UPDATED_BY BIGINT;

-- GW_ATTACH: CREATED_AT/BY 만 → 삭제 추적용 DELETED_AT
ALTER TABLE GW_ATTACH ADD COLUMN IF NOT EXISTS DELETED_AT TIMESTAMP;
ALTER TABLE GW_ATTACH ADD COLUMN IF NOT EXISTS UPDATED_AT TIMESTAMP;
