-- 데이터 무결성 — 외래키 제약 일괄 추가
-- 시드된 마스터(GW_DEPT/POSITION/MENU/ROOM/USER) 와 그것을 참조하는 트랜잭션 테이블 사이에
-- DB 수준 참조 무결성을 강제한다.
--
-- 일부 V6/V7 시드는 DataInitializer 가 사용자(GW_USER) 를 채우기 전에 데이터를 넣어 둔다.
-- 즉 본 마이그레이션 시점에 user_id/vendor_id 가 '아직 만들어지지 않은 부모 PK' 를 가리키는
-- 위반 row 가 존재할 수 있다. 이 위반들은 부팅 후 DataInitializer 가 user 를 만든 뒤에야
-- 해소되므로, 마이그레이션 시점에 FK 를 부여하면 무결성 검사가 즉시 실패한다.
-- → 시드된 row 의 참조키 중 부모에 없는 값은 NULL 로 사전 보정한 뒤 FK 를 건다.

-- ========== 0. 위반 row 사전 정리 ==========
-- (NULL 허용 컬럼만 NULL 로 치환, NOT NULL 컬럼은 DELETE)
UPDATE gw_asset SET assigned_user_id = NULL
 WHERE assigned_user_id IS NOT NULL
   AND assigned_user_id NOT IN (SELECT user_id FROM gw_user);

DELETE FROM gw_vehicle_reservation
 WHERE user_id NOT IN (SELECT user_id FROM gw_user);

DELETE FROM gw_invoice
 WHERE vendor_id NOT IN (SELECT vendor_id FROM gw_vendor);

DELETE FROM gw_biz_contract
 WHERE vendor_id NOT IN (SELECT vendor_id FROM gw_vendor);

DELETE FROM gw_billing_schedule
 WHERE biz_contract_id NOT IN (SELECT biz_contract_id FROM gw_biz_contract);

UPDATE gw_payment SET invoice_id = NULL
 WHERE invoice_id IS NOT NULL
   AND invoice_id NOT IN (SELECT invoice_id FROM gw_invoice);

--
-- 정책:
--  ON DELETE RESTRICT — 사용자/계약/기간 등 보존이 중요한 부모. 자식이 있으면 부모 삭제 차단.
--  ON DELETE CASCADE  — 부모 라이프사이클을 함께 가는 자식 (예: 급여→급여항목, 결재→결재선).
--  ON DELETE SET NULL — 부모가 폐기돼도 자식은 유지 (예: 부서 폐지·매니저 변경).

-- ========== 사용자/조직 마스터 (소프트 — SET NULL) ==========
ALTER TABLE GW_USER         ADD CONSTRAINT FK_USER_DEPT          FOREIGN KEY (DEPT_ID)     REFERENCES GW_DEPT(DEPT_ID)         ON DELETE SET NULL;
ALTER TABLE GW_USER         ADD CONSTRAINT FK_USER_POSITION      FOREIGN KEY (POSITION_ID) REFERENCES GW_POSITION(POSITION_ID) ON DELETE SET NULL;
ALTER TABLE GW_DEPT         ADD CONSTRAINT FK_DEPT_PARENT        FOREIGN KEY (PARENT_ID)         REFERENCES GW_DEPT(DEPT_ID)   ON DELETE SET NULL;
ALTER TABLE GW_DEPT         ADD CONSTRAINT FK_DEPT_MANAGER       FOREIGN KEY (MANAGER_USER_ID)   REFERENCES GW_USER(USER_ID)   ON DELETE SET NULL;
ALTER TABLE GW_MENU         ADD CONSTRAINT FK_MENU_PARENT        FOREIGN KEY (PARENT_ID)         REFERENCES GW_MENU(MENU_ID)   ON DELETE SET NULL;

-- ========== 휴가 ==========
ALTER TABLE GW_LEAVE_REQ      ADD CONSTRAINT FK_LEAVE_REQ_USER     FOREIGN KEY (USER_ID) REFERENCES GW_USER(USER_ID) ON DELETE RESTRICT;
ALTER TABLE GW_LEAVE_BALANCE  ADD CONSTRAINT FK_LEAVE_BAL_USER     FOREIGN KEY (USER_ID) REFERENCES GW_USER(USER_ID) ON DELETE CASCADE;

-- ========== 부양가족 / 인사 카드 ==========
ALTER TABLE GW_FAMILY         ADD CONSTRAINT FK_FAMILY_USER        FOREIGN KEY (USER_ID) REFERENCES GW_USER(USER_ID) ON DELETE CASCADE;
ALTER TABLE GW_HR_RECORD      ADD CONSTRAINT FK_HR_RECORD_USER     FOREIGN KEY (USER_ID) REFERENCES GW_USER(USER_ID) ON DELETE RESTRICT;
ALTER TABLE GW_HR_HISTORY     ADD CONSTRAINT FK_HR_HISTORY_USER    FOREIGN KEY (USER_ID) REFERENCES GW_USER(USER_ID) ON DELETE RESTRICT;

-- V11 인사 부속 (모두 사용자 기준)
ALTER TABLE GW_HR_CAREER      ADD CONSTRAINT FK_HR_CAREER_USER     FOREIGN KEY (USER_ID) REFERENCES GW_USER(USER_ID) ON DELETE CASCADE;
ALTER TABLE GW_HR_EDUCATION   ADD CONSTRAINT FK_HR_EDU_USER        FOREIGN KEY (USER_ID) REFERENCES GW_USER(USER_ID) ON DELETE CASCADE;
ALTER TABLE GW_HR_TRAINING    ADD CONSTRAINT FK_HR_TRN_USER        FOREIGN KEY (USER_ID) REFERENCES GW_USER(USER_ID) ON DELETE CASCADE;
ALTER TABLE GW_HR_AWARD       ADD CONSTRAINT FK_HR_AWARD_USER      FOREIGN KEY (USER_ID) REFERENCES GW_USER(USER_ID) ON DELETE RESTRICT;

-- ========== 급여/근로계약 ==========
ALTER TABLE GW_SALARY_CONTRACT     ADD CONSTRAINT FK_SAL_CONTRACT_USER   FOREIGN KEY (USER_ID)     REFERENCES GW_USER(USER_ID)                ON DELETE RESTRICT;
ALTER TABLE GW_PAYROLL             ADD CONSTRAINT FK_PAYROLL_USER        FOREIGN KEY (USER_ID)     REFERENCES GW_USER(USER_ID)                ON DELETE RESTRICT;
ALTER TABLE GW_PAYROLL             ADD CONSTRAINT FK_PAYROLL_CONTRACT    FOREIGN KEY (CONTRACT_ID) REFERENCES GW_SALARY_CONTRACT(CONTRACT_ID) ON DELETE SET NULL;
ALTER TABLE GW_PAYROLL_ITEM        ADD CONSTRAINT FK_PAYROLL_ITEM_PAY    FOREIGN KEY (PAY_ID)      REFERENCES GW_PAYROLL(PAY_ID)              ON DELETE CASCADE;
ALTER TABLE GW_EMPLOYMENT_CONTRACT ADD CONSTRAINT FK_EMP_CONTRACT_USER   FOREIGN KEY (USER_ID)     REFERENCES GW_USER(USER_ID)                ON DELETE RESTRICT;
ALTER TABLE GW_EMPLOYMENT_CONTRACT ADD CONSTRAINT FK_EMP_CONTRACT_SALARY FOREIGN KEY (SALARY_CONTRACT_ID) REFERENCES GW_SALARY_CONTRACT(CONTRACT_ID) ON DELETE SET NULL;

-- ========== 결재 ==========
ALTER TABLE GW_APPROVAL_DOC   ADD CONSTRAINT FK_APPR_DOC_DRAFTER  FOREIGN KEY (DRAFTER_ID) REFERENCES GW_USER(USER_ID)         ON DELETE RESTRICT;
ALTER TABLE GW_APPROVAL_LINE  ADD CONSTRAINT FK_APPR_LINE_DOC     FOREIGN KEY (DOC_ID)     REFERENCES GW_APPROVAL_DOC(DOC_ID)  ON DELETE CASCADE;
ALTER TABLE GW_APPROVAL_LINE  ADD CONSTRAINT FK_APPR_LINE_USER    FOREIGN KEY (APPROVER_ID) REFERENCES GW_USER(USER_ID)        ON DELETE RESTRICT;

-- ========== 협업/공지/게시판 ==========
ALTER TABLE GW_NOTICE          ADD CONSTRAINT FK_NOTICE_AUTHOR    FOREIGN KEY (AUTHOR_ID)  REFERENCES GW_USER(USER_ID)         ON DELETE RESTRICT;
ALTER TABLE GW_NOTICE_COMMENT  ADD CONSTRAINT FK_NOTICE_CMT_NOTICE FOREIGN KEY (NOTICE_ID) REFERENCES GW_NOTICE(NOTICE_ID)     ON DELETE CASCADE;
ALTER TABLE GW_NOTICE_COMMENT  ADD CONSTRAINT FK_NOTICE_CMT_AUTHOR FOREIGN KEY (AUTHOR_ID) REFERENCES GW_USER(USER_ID)         ON DELETE RESTRICT;
ALTER TABLE gw_board_post     ADD CONSTRAINT FK_POST_AUTHOR    FOREIGN KEY (author_id) REFERENCES GW_USER(USER_ID)        ON DELETE RESTRICT;
ALTER TABLE gw_board_comment  ADD CONSTRAINT FK_POST_CMT_POST  FOREIGN KEY (post_id)   REFERENCES gw_board_post(post_id)  ON DELETE CASCADE;
ALTER TABLE gw_board_comment  ADD CONSTRAINT FK_POST_CMT_USER  FOREIGN KEY (author_id) REFERENCES GW_USER(USER_ID)        ON DELETE RESTRICT;

-- ========== 일정/회의실/쪽지/알림 ==========
ALTER TABLE GW_CAL_EVENT  ADD CONSTRAINT FK_CAL_EVT_OWNER   FOREIGN KEY (OWNER_ID) REFERENCES GW_USER(USER_ID) ON DELETE CASCADE;
ALTER TABLE GW_ROOM_RES   ADD CONSTRAINT FK_ROOM_RES_ROOM   FOREIGN KEY (ROOM_ID)  REFERENCES GW_ROOM(ROOM_ID) ON DELETE RESTRICT;
ALTER TABLE GW_ROOM_RES   ADD CONSTRAINT FK_ROOM_RES_USER   FOREIGN KEY (USER_ID)  REFERENCES GW_USER(USER_ID) ON DELETE CASCADE;
ALTER TABLE GW_MESSAGE    ADD CONSTRAINT FK_MSG_SENDER      FOREIGN KEY (SENDER_ID)   REFERENCES GW_USER(USER_ID) ON DELETE RESTRICT;
ALTER TABLE GW_MESSAGE    ADD CONSTRAINT FK_MSG_RECEIVER    FOREIGN KEY (RECEIVER_ID) REFERENCES GW_USER(USER_ID) ON DELETE RESTRICT;
ALTER TABLE GW_NOTIFICATION ADD CONSTRAINT FK_NOTI_USER     FOREIGN KEY (USER_ID) REFERENCES GW_USER(USER_ID) ON DELETE CASCADE;

-- ========== 근태/평가/성과 ==========
ALTER TABLE GW_ATTENDANCE  ADD CONSTRAINT FK_ATTEND_USER   FOREIGN KEY (USER_ID)   REFERENCES GW_USER(USER_ID)         ON DELETE RESTRICT;
ALTER TABLE GW_EVAL        ADD CONSTRAINT FK_EVAL_PERIOD   FOREIGN KEY (PERIOD_ID) REFERENCES GW_EVAL_PERIOD(PERIOD_ID) ON DELETE RESTRICT;
ALTER TABLE GW_PERF        ADD CONSTRAINT FK_PERF_PERIOD   FOREIGN KEY (PERIOD_ID) REFERENCES GW_EVAL_PERIOD(PERIOD_ID) ON DELETE RESTRICT;

-- ========== 자산/차량 (V7 — 소문자 테이블) ==========
ALTER TABLE gw_asset                 ADD CONSTRAINT fk_asset_user        FOREIGN KEY (assigned_user_id) REFERENCES GW_USER(USER_ID) ON DELETE SET NULL;
ALTER TABLE gw_vehicle_reservation   ADD CONSTRAINT fk_veh_res_user      FOREIGN KEY (user_id)    REFERENCES GW_USER(USER_ID)    ON DELETE RESTRICT;
ALTER TABLE gw_vehicle_reservation   ADD CONSTRAINT fk_veh_res_vehicle   FOREIGN KEY (vehicle_id) REFERENCES gw_vehicle(vehicle_id) ON DELETE RESTRICT;

-- ========== 재무/거래처 ==========
ALTER TABLE GW_INVOICE      ADD CONSTRAINT FK_INVOICE_VENDOR    FOREIGN KEY (VENDOR_ID) REFERENCES GW_VENDOR(VENDOR_ID) ON DELETE RESTRICT;
ALTER TABLE GW_BIZ_CONTRACT ADD CONSTRAINT FK_BIZ_CONTRACT_VEND FOREIGN KEY (VENDOR_ID) REFERENCES GW_VENDOR(VENDOR_ID) ON DELETE RESTRICT;
ALTER TABLE GW_PAYMENT      ADD CONSTRAINT FK_PAYMENT_INVOICE   FOREIGN KEY (INVOICE_ID) REFERENCES GW_INVOICE(INVOICE_ID) ON DELETE SET NULL;
