-- 휴가 모듈 보강
-- 1) 반차에 오전/오후(AM/PM) 구분 추가
-- 2) HALF_TYPE 코드 그룹 시드

ALTER TABLE GW_LEAVE_REQ ADD COLUMN IF NOT EXISTS HALF_TYPE_CD VARCHAR(2);

INSERT INTO GW_CODE_GROUP (GROUP_CD, GROUP_NM, DESCRIPTION) VALUES
 ('HALF_TYPE','반차 구분','오전(AM)/오후(PM)');

INSERT INTO GW_CODE (GROUP_CD, CODE_VAL, CODE_NM, SORT_NO) VALUES
 ('HALF_TYPE','AM','오전 반차',1),
 ('HALF_TYPE','PM','오후 반차',2);
