-- =============================================================
--  사내 그룹웨어 V1 초기 스키마
--  PostgreSQL 16 기준 (H2 MODE=PostgreSQL 호환). H2 비호환 제약은 migration-h2/ 또는 V_xx_pg_only.sql 분리.
-- =============================================================

-- 1. 멀티테넌시 / 마스터
CREATE TABLE GW_TENANT (
    TENANT_ID    BIGSERIAL PRIMARY KEY,
    TENANT_NM    VARCHAR(100) NOT NULL,
    USE_YN       CHAR(1) NOT NULL DEFAULT 'Y',
    CREATED_AT   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT   TIMESTAMP
);

CREATE TABLE GW_DEPT (
    DEPT_ID         BIGSERIAL PRIMARY KEY,
    DEPT_NM         VARCHAR(100) NOT NULL,
    PARENT_ID       BIGINT,
    SORT_NO         INT NOT NULL DEFAULT 0,
    MANAGER_USER_ID BIGINT,
    USE_YN          CHAR(1) NOT NULL DEFAULT 'Y',
    TENANT_ID       BIGINT NOT NULL DEFAULT 1,
    CREATED_AT      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY      BIGINT,
    UPDATED_AT      TIMESTAMP,
    UPDATED_BY      BIGINT,
    DELETED_AT      TIMESTAMP
);

CREATE TABLE GW_POSITION (
    POSITION_ID  BIGSERIAL PRIMARY KEY,
    POSITION_NM  VARCHAR(50) NOT NULL,
    LEVEL_NO     INT NOT NULL,
    USE_YN       CHAR(1) NOT NULL DEFAULT 'Y',
    CREATED_AT   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT   TIMESTAMP
);

CREATE TABLE GW_ROLE (
    ROLE_CD      VARCHAR(30) PRIMARY KEY,
    ROLE_NM      VARCHAR(50) NOT NULL,
    DESCRIPTION  VARCHAR(200),
    SORT_NO      INT NOT NULL DEFAULT 0
);

CREATE TABLE GW_MENU (
    MENU_ID    BIGSERIAL PRIMARY KEY,
    MENU_NM    VARCHAR(100) NOT NULL,
    URL        VARCHAR(255),
    PARENT_ID  BIGINT,
    SORT_NO    INT NOT NULL DEFAULT 0,
    ICON       VARCHAR(50),
    USE_YN     CHAR(1) NOT NULL DEFAULT 'Y',
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE GW_MENU_ROLE (
    MENU_ID  BIGINT NOT NULL,
    ROLE_CD  VARCHAR(30) NOT NULL,
    PRIMARY KEY (MENU_ID, ROLE_CD)
);

CREATE TABLE GW_CODE_GROUP (
    GROUP_CD     VARCHAR(50) PRIMARY KEY,
    GROUP_NM     VARCHAR(100) NOT NULL,
    DESCRIPTION  VARCHAR(255),
    USE_YN       CHAR(1) NOT NULL DEFAULT 'Y'
);

CREATE TABLE GW_CODE (
    CODE_ID    BIGSERIAL PRIMARY KEY,
    GROUP_CD   VARCHAR(50) NOT NULL,
    CODE_VAL   VARCHAR(50) NOT NULL,
    CODE_NM    VARCHAR(100) NOT NULL,
    SORT_NO    INT NOT NULL DEFAULT 0,
    USE_YN     CHAR(1) NOT NULL DEFAULT 'Y',
    EXTRA_VAL  VARCHAR(255)
);
CREATE UNIQUE INDEX UX_GW_CODE_GROUP_VAL ON GW_CODE(GROUP_CD, CODE_VAL);

-- 2. 사용자/인증
CREATE TABLE GW_USER (
    USER_ID          BIGSERIAL PRIMARY KEY,
    EMAIL            VARCHAR(150) NOT NULL,
    PASSWORD_HASH    VARCHAR(255) NOT NULL,
    NAME             VARCHAR(50)  NOT NULL,
    PHONE            VARCHAR(30),
    DEPT_ID          BIGINT,
    POSITION_ID      BIGINT,
    ROLE_CD          VARCHAR(30) NOT NULL,
    HIRE_DATE        DATE,
    BANK_CD          VARCHAR(10),
    BANK_ACCOUNT     VARCHAR(50),
    USE_YN           CHAR(1) NOT NULL DEFAULT 'Y',
    PWD_FAIL_CNT     INT NOT NULL DEFAULT 0,
    LOCKED_YN        CHAR(1) NOT NULL DEFAULT 'N',
    LOCKED_AT        TIMESTAMP,
    PWD_CHANGED_AT   TIMESTAMP,
    PWD_EXPIRE_AT    TIMESTAMP,
    LAST_LOGIN_AT    TIMESTAMP,
    LAST_LOGIN_IP    VARCHAR(50),
    TENANT_ID        BIGINT NOT NULL DEFAULT 1,
    CREATED_AT       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY       BIGINT,
    UPDATED_AT       TIMESTAMP,
    UPDATED_BY       BIGINT,
    DELETED_AT       TIMESTAMP
);
CREATE UNIQUE INDEX UX_GW_USER_EMAIL ON GW_USER(EMAIL);
CREATE INDEX IX_GW_USER_DEPT ON GW_USER(DEPT_ID, USE_YN);

CREATE TABLE GW_USER_PWD_HIST (
    HIST_ID       BIGSERIAL PRIMARY KEY,
    USER_ID       BIGINT NOT NULL,
    PASSWORD_HASH VARCHAR(255) NOT NULL,
    CHANGED_AT    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IX_GW_USER_PWD_HIST_USER ON GW_USER_PWD_HIST(USER_ID, CHANGED_AT DESC);

CREATE TABLE GW_LOGIN_LOG (
    LOG_ID       BIGSERIAL PRIMARY KEY,
    USER_ID      BIGINT,
    EMAIL_INPUT  VARCHAR(150),
    LOGIN_DT     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    IP           VARCHAR(50),
    USER_AGENT   VARCHAR(500),
    SUCCESS_YN   CHAR(1) NOT NULL,
    FAIL_REASON  VARCHAR(100)
);
CREATE INDEX IX_GW_LOGIN_LOG_USER ON GW_LOGIN_LOG(USER_ID, LOGIN_DT DESC);

CREATE TABLE GW_AUDIT_LOG (
    AUDIT_ID    BIGSERIAL PRIMARY KEY,
    USER_ID     BIGINT,
    ACTION_TYPE VARCHAR(30) NOT NULL,
    ENTITY_NAME VARCHAR(100),
    ENTITY_ID   VARCHAR(100),
    BEFORE_JSON TEXT,
    AFTER_JSON  TEXT,
    IP          VARCHAR(50),
    ACTION_AT   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IX_GW_AUDIT_ENTITY ON GW_AUDIT_LOG(ENTITY_NAME, ENTITY_ID, ACTION_AT DESC);
CREATE INDEX IX_GW_AUDIT_USER ON GW_AUDIT_LOG(USER_ID, ACTION_AT DESC);

-- 3. 첨부 / 알림
CREATE TABLE GW_ATTACH_GROUP (
    GROUP_ID         BIGSERIAL PRIMARY KEY,
    OWNER_ENTITY     VARCHAR(50),
    OWNER_ENTITY_ID  VARCHAR(100),
    CREATED_AT       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE GW_ATTACH (
    ATTACH_ID    BIGSERIAL PRIMARY KEY,
    GROUP_ID     BIGINT NOT NULL,
    FILE_NM      VARCHAR(255) NOT NULL,
    STORED_NM    VARCHAR(255) NOT NULL,
    FILE_SIZE    BIGINT NOT NULL,
    MIME_TYPE    VARCHAR(100),
    STORAGE_TYPE VARCHAR(20) NOT NULL DEFAULT 'LOCAL',
    STORED_PATH  VARCHAR(500),
    CHECKSUM     VARCHAR(100),
    CREATED_AT   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY   BIGINT
);
CREATE INDEX IX_GW_ATTACH_GROUP ON GW_ATTACH(GROUP_ID);

CREATE TABLE GW_NOTIFICATION (
    NOTI_ID    BIGSERIAL PRIMARY KEY,
    USER_ID    BIGINT NOT NULL,
    TYPE_CD    VARCHAR(30) NOT NULL,
    TITLE      VARCHAR(200) NOT NULL,
    BODY       VARCHAR(500),
    LINK_URL   VARCHAR(255),
    READ_AT    TIMESTAMP,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IX_GW_NOTI_USER ON GW_NOTIFICATION(USER_ID, READ_AT, CREATED_AT DESC);

-- 4. 공지 / 댓글
CREATE TABLE GW_NOTICE (
    NOTICE_ID        BIGSERIAL PRIMARY KEY,
    TITLE            VARCHAR(200) NOT NULL,
    CONTENT          TEXT NOT NULL,
    AUTHOR_ID        BIGINT NOT NULL,
    PINNED_YN        CHAR(1) NOT NULL DEFAULT 'N',
    VIEW_CNT         INT NOT NULL DEFAULT 0,
    ATTACH_GROUP_ID  BIGINT,
    DEPT_SCOPE       VARCHAR(20),
    CREATED_AT       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY       BIGINT,
    UPDATED_AT       TIMESTAMP,
    UPDATED_BY       BIGINT,
    DELETED_AT       TIMESTAMP
);
CREATE INDEX IX_GW_NOTICE_LIST ON GW_NOTICE(PINNED_YN DESC, CREATED_AT DESC);

CREATE TABLE GW_NOTICE_COMMENT (
    CMT_ID     BIGSERIAL PRIMARY KEY,
    NOTICE_ID  BIGINT NOT NULL,
    AUTHOR_ID  BIGINT NOT NULL,
    CONTENT    VARCHAR(1000) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DELETED_AT TIMESTAMP
);
CREATE INDEX IX_GW_NOTICE_CMT ON GW_NOTICE_COMMENT(NOTICE_ID, CREATED_AT);

-- 5. 캘린더
CREATE TABLE GW_CAL_EVENT (
    EVT_ID     BIGSERIAL PRIMARY KEY,
    TITLE      VARCHAR(200) NOT NULL,
    START_DT   TIMESTAMP NOT NULL,
    END_DT     TIMESTAMP NOT NULL,
    SCOPE_CD   VARCHAR(20) NOT NULL,
    OWNER_ID   BIGINT NOT NULL,
    DEPT_ID    BIGINT,
    COLOR      VARCHAR(20),
    MEMO       VARCHAR(1000),
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY BIGINT,
    UPDATED_AT TIMESTAMP,
    DELETED_AT TIMESTAMP
);
CREATE INDEX IX_GW_CAL_OWNER ON GW_CAL_EVENT(OWNER_ID, START_DT);
CREATE INDEX IX_GW_CAL_DEPT ON GW_CAL_EVENT(DEPT_ID, START_DT);

-- 6. 휴가
CREATE TABLE GW_LEAVE_REQ (
    LEAVE_ID         BIGSERIAL PRIMARY KEY,
    USER_ID          BIGINT NOT NULL,
    LEAVE_TYPE_CD    VARCHAR(20) NOT NULL,
    START_DT         DATE NOT NULL,
    END_DT           DATE NOT NULL,
    DAYS             NUMERIC(4,1) NOT NULL,
    REASON           VARCHAR(500),
    STATUS_CD        VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    APPROVAL_DOC_ID  BIGINT,
    CREATED_AT       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY       BIGINT,
    UPDATED_AT       TIMESTAMP,
    DELETED_AT       TIMESTAMP
);
CREATE INDEX IX_GW_LEAVE_USER ON GW_LEAVE_REQ(USER_ID, START_DT DESC);

CREATE TABLE GW_LEAVE_BALANCE (
    USER_ID        BIGINT NOT NULL,
    BAL_YEAR       INT NOT NULL,
    ANNUAL_GIVEN   NUMERIC(4,1) NOT NULL DEFAULT 15,
    ANNUAL_USED    NUMERIC(4,1) NOT NULL DEFAULT 0,
    UPDATED_AT     TIMESTAMP,
    PRIMARY KEY (USER_ID, BAL_YEAR)
);

-- 7. 전자결재
CREATE TABLE GW_APPROVAL_FORM (
    FORM_ID    BIGSERIAL PRIMARY KEY,
    FORM_CD    VARCHAR(50) NOT NULL,
    FORM_NM    VARCHAR(100) NOT NULL,
    FIELDS_JSON TEXT,
    USE_YN     CHAR(1) NOT NULL DEFAULT 'Y'
);
CREATE UNIQUE INDEX UX_GW_APPROVAL_FORM_CD ON GW_APPROVAL_FORM(FORM_CD);

CREATE TABLE GW_APPROVAL_DOC (
    DOC_ID       BIGSERIAL PRIMARY KEY,
    DOC_NO       VARCHAR(50) NOT NULL,
    FORM_ID      BIGINT NOT NULL,
    TITLE        VARCHAR(200) NOT NULL,
    CONTENT_JSON TEXT,
    DRAFTER_ID   BIGINT NOT NULL,
    STATUS_CD    VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    SUBMITTED_AT TIMESTAMP,
    COMPLETED_AT TIMESTAMP,
    CREATED_AT   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY   BIGINT,
    UPDATED_AT   TIMESTAMP,
    DELETED_AT   TIMESTAMP
);
CREATE UNIQUE INDEX UX_GW_APPROVAL_DOC_NO ON GW_APPROVAL_DOC(DOC_NO);
CREATE INDEX IX_GW_APPROVAL_DRAFTER ON GW_APPROVAL_DOC(DRAFTER_ID, CREATED_AT DESC);
CREATE INDEX IX_GW_APPROVAL_STATUS ON GW_APPROVAL_DOC(STATUS_CD);

CREATE TABLE GW_APPROVAL_LINE (
    LINE_ID                BIGSERIAL PRIMARY KEY,
    DOC_ID                 BIGINT NOT NULL,
    STEP_NO                INT NOT NULL,
    APPROVER_ID            BIGINT NOT NULL,
    LINE_TYPE_CD           VARCHAR(20) NOT NULL DEFAULT 'APPROVE',
    STATUS_CD              VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    COMMENT                VARCHAR(1000),
    ACTED_AT               TIMESTAMP,
    DELEGATED_TO_USER_ID   BIGINT
);
CREATE INDEX IX_GW_APPROVAL_LINE_APPROVER ON GW_APPROVAL_LINE(APPROVER_ID, STATUS_CD);
CREATE INDEX IX_GW_APPROVAL_LINE_DOC ON GW_APPROVAL_LINE(DOC_ID, STEP_NO);

CREATE TABLE GW_APPROVAL_DELEGATE (
    DELEGATE_ID            BIGSERIAL PRIMARY KEY,
    USER_ID                BIGINT NOT NULL,
    DELEGATED_TO_USER_ID   BIGINT NOT NULL,
    START_DT               DATE NOT NULL,
    END_DT                 DATE NOT NULL,
    ACTIVE_YN              CHAR(1) NOT NULL DEFAULT 'Y',
    CREATED_AT             TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 8. 근태
CREATE TABLE GW_ATTENDANCE (
    ATT_ID       BIGSERIAL PRIMARY KEY,
    USER_ID      BIGINT NOT NULL,
    WORK_DT      DATE NOT NULL,
    CHECK_IN     TIMESTAMP,
    CHECK_OUT    TIMESTAMP,
    STATUS_CD    VARCHAR(20) NOT NULL DEFAULT 'NORMAL',
    WORK_MIN     INT NOT NULL DEFAULT 0,
    OT_MIN       INT NOT NULL DEFAULT 0,
    NIGHT_MIN    INT NOT NULL DEFAULT 0,
    HOLIDAY_MIN  INT NOT NULL DEFAULT 0,
    REMARK       VARCHAR(255),
    CREATED_AT   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT   TIMESTAMP
);
CREATE UNIQUE INDEX UX_GW_ATT_USER_DATE ON GW_ATTENDANCE(USER_ID, WORK_DT);

-- 9. 급여
CREATE TABLE GW_SALARY_CONTRACT (
    CONTRACT_ID       BIGSERIAL PRIMARY KEY,
    USER_ID           BIGINT NOT NULL,
    START_DT          DATE NOT NULL,
    END_DT            DATE,
    ANNUAL_SALARY     NUMERIC(14,0) NOT NULL,
    MONTHLY_BASE_SAL  NUMERIC(14,0) NOT NULL,
    DIVISION_TYPE_CD  VARCHAR(10) NOT NULL DEFAULT '12',
    PAYMENT_DAY       INT NOT NULL DEFAULT 25,
    NOTE              VARCHAR(255),
    CREATED_AT        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY        BIGINT
);
CREATE INDEX IX_GW_SAL_CONTRACT_USER ON GW_SALARY_CONTRACT(USER_ID, START_DT DESC);

CREATE TABLE GW_INSURANCE_RATE (
    RATE_ID         BIGSERIAL PRIMARY KEY,
    INSURANCE_CD    VARCHAR(10) NOT NULL,
    EFFECTIVE_FROM  DATE NOT NULL,
    EFFECTIVE_TO    DATE,
    EMPLOYEE_RATE   NUMERIC(7,5) NOT NULL,
    EMPLOYER_RATE   NUMERIC(7,5) NOT NULL DEFAULT 0,
    BASE_MIN        NUMERIC(14,0),
    BASE_MAX        NUMERIC(14,0),
    NOTE            VARCHAR(255)
);
CREATE INDEX IX_GW_INS_RATE_CD ON GW_INSURANCE_RATE(INSURANCE_CD, EFFECTIVE_FROM DESC);

CREATE TABLE GW_FAMILY (
    FAM_ID        BIGSERIAL PRIMARY KEY,
    USER_ID       BIGINT NOT NULL,
    RELATION_CD   VARCHAR(20) NOT NULL,
    NAME          VARCHAR(50) NOT NULL,
    BIRTH_DT      DATE,
    DEPENDENT_YN  CHAR(1) NOT NULL DEFAULT 'Y',
    ELDERLY_YN    CHAR(1) NOT NULL DEFAULT 'N',
    DISABLED_YN   CHAR(1) NOT NULL DEFAULT 'N',
    CREATED_AT    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IX_GW_FAMILY_USER ON GW_FAMILY(USER_ID);

CREATE TABLE GW_PAYROLL (
    PAY_ID            BIGSERIAL PRIMARY KEY,
    USER_ID           BIGINT NOT NULL,
    PAY_MONTH         CHAR(7) NOT NULL,
    CONTRACT_ID       BIGINT,
    WORK_DAYS         NUMERIC(4,1) NOT NULL DEFAULT 0,
    ABSENT_DAYS       NUMERIC(4,1) NOT NULL DEFAULT 0,
    OT_MIN            INT NOT NULL DEFAULT 0,
    NIGHT_MIN         INT NOT NULL DEFAULT 0,
    HOLIDAY_MIN       INT NOT NULL DEFAULT 0,
    TAXABLE_PAY       NUMERIC(14,0) NOT NULL DEFAULT 0,
    NON_TAXABLE_PAY   NUMERIC(14,0) NOT NULL DEFAULT 0,
    GROSS_PAY         NUMERIC(14,0) NOT NULL DEFAULT 0,
    DEDUCTION_TOTAL   NUMERIC(14,0) NOT NULL DEFAULT 0,
    NET_PAY           NUMERIC(14,0) NOT NULL DEFAULT 0,
    STATUS_CD         VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    PAID_DT           DATE,
    MEMO              VARCHAR(500),
    CREATED_AT        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY        BIGINT,
    UPDATED_AT        TIMESTAMP,
    UPDATED_BY        BIGINT
);
CREATE UNIQUE INDEX UX_GW_PAYROLL_USER_MONTH ON GW_PAYROLL(USER_ID, PAY_MONTH);

CREATE TABLE GW_PAYROLL_ITEM (
    ITEM_ID     BIGSERIAL PRIMARY KEY,
    PAY_ID      BIGINT NOT NULL,
    KIND_CD     VARCHAR(20) NOT NULL,
    CODE_VAL    VARCHAR(50) NOT NULL,
    ITEM_NM     VARCHAR(100) NOT NULL,
    AMOUNT      NUMERIC(14,0) NOT NULL DEFAULT 0,
    TAXABLE_YN  CHAR(1) NOT NULL DEFAULT 'Y',
    AUTO_YN     CHAR(1) NOT NULL DEFAULT 'Y',
    SORT_NO     INT NOT NULL DEFAULT 0,
    MEMO        VARCHAR(255)
);
CREATE INDEX IX_GW_PAYROLL_ITEM_PAY ON GW_PAYROLL_ITEM(PAY_ID, KIND_CD, SORT_NO);

CREATE TABLE GW_PAYROLL_EMPLOYER_COST (
    PAY_ID        BIGINT NOT NULL,
    INSURANCE_CD  VARCHAR(10) NOT NULL,
    AMOUNT        NUMERIC(14,0) NOT NULL DEFAULT 0,
    PRIMARY KEY (PAY_ID, INSURANCE_CD)
);

-- 10. 인사기록 / 이력
CREATE TABLE GW_HR_RECORD (
    REC_ID      BIGSERIAL PRIMARY KEY,
    USER_ID     BIGINT NOT NULL,
    CATEGORY_CD VARCHAR(20) NOT NULL,
    TITLE       VARCHAR(200) NOT NULL,
    CONTENT     TEXT,
    EVENT_DT    DATE,
    CREATED_AT  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IX_GW_HR_REC_USER ON GW_HR_RECORD(USER_ID, EVENT_DT DESC);

CREATE TABLE GW_HR_HISTORY (
    HIS_ID         BIGSERIAL PRIMARY KEY,
    USER_ID        BIGINT NOT NULL,
    CHANGE_TYPE_CD VARCHAR(20) NOT NULL,
    BEFORE_JSON    TEXT,
    AFTER_JSON     TEXT,
    EFFECTIVE_DT   DATE NOT NULL,
    CREATED_AT     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY     BIGINT
);
CREATE INDEX IX_GW_HR_HIS_USER ON GW_HR_HISTORY(USER_ID, EFFECTIVE_DT DESC);

-- 11. 평가 / 성과
CREATE TABLE GW_EVAL_PERIOD (
    PERIOD_ID  BIGSERIAL PRIMARY KEY,
    PERIOD_NM  VARCHAR(50) NOT NULL,
    START_DT   DATE NOT NULL,
    END_DT     DATE NOT NULL,
    STATUS_CD  VARCHAR(20) NOT NULL DEFAULT 'PLANNED'
);

CREATE TABLE GW_EVAL_FORM (
    FORM_ID    BIGSERIAL PRIMARY KEY,
    FORM_NM    VARCHAR(100) NOT NULL,
    ITEMS_JSON TEXT
);

CREATE TABLE GW_EVAL (
    EVAL_ID       BIGSERIAL PRIMARY KEY,
    PERIOD_ID     BIGINT NOT NULL,
    EVALUATEE_ID  BIGINT NOT NULL,
    EVALUATOR_ID  BIGINT NOT NULL,
    SCORES_JSON   TEXT,
    FINAL_SCORE   NUMERIC(5,2),
    GRADE_CD      VARCHAR(10),
    COMMENT       VARCHAR(2000),
    CREATED_AT    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT    TIMESTAMP
);
CREATE INDEX IX_GW_EVAL_PERIOD ON GW_EVAL(PERIOD_ID, EVALUATEE_ID);

CREATE TABLE GW_PERF (
    PERF_ID    BIGSERIAL PRIMARY KEY,
    USER_ID    BIGINT NOT NULL,
    PERIOD_ID  BIGINT NOT NULL,
    GOAL       VARCHAR(500) NOT NULL,
    KPI        VARCHAR(200) NOT NULL,
    UNIT       VARCHAR(30),
    TARGET_VAL NUMERIC(14,2),
    ACTUAL_VAL NUMERIC(14,2),
    ACH_RATE   NUMERIC(5,2),
    WEIGHT     NUMERIC(5,2) NOT NULL DEFAULT 100,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IX_GW_PERF_USER ON GW_PERF(USER_ID, PERIOD_ID);

-- 12. 회의실
CREATE TABLE GW_ROOM (
    ROOM_ID    BIGSERIAL PRIMARY KEY,
    ROOM_NM    VARCHAR(100) NOT NULL,
    CAPACITY   INT NOT NULL DEFAULT 0,
    LOCATION   VARCHAR(100),
    EQUIPMENTS VARCHAR(500),
    USE_YN     CHAR(1) NOT NULL DEFAULT 'Y',
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE GW_ROOM_RES (
    RES_ID     BIGSERIAL PRIMARY KEY,
    ROOM_ID    BIGINT NOT NULL,
    USER_ID    BIGINT NOT NULL,
    START_DT   TIMESTAMP NOT NULL,
    END_DT     TIMESTAMP NOT NULL,
    PURPOSE    VARCHAR(255),
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DELETED_AT TIMESTAMP
);
CREATE INDEX IX_GW_ROOM_RES_TIME ON GW_ROOM_RES(ROOM_ID, START_DT);
-- PostgreSQL 전용 EXCLUDE 제약은 별도 (V_pg_only / migration-pg)

-- 13. 쪽지
CREATE TABLE GW_MESSAGE (
    MSG_ID      BIGSERIAL PRIMARY KEY,
    SENDER_ID   BIGINT NOT NULL,
    RECEIVER_ID BIGINT NOT NULL,
    CONTENT     VARCHAR(2000) NOT NULL,
    READ_AT     TIMESTAMP,
    CREATED_AT  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DELETED_AT  TIMESTAMP
);
CREATE INDEX IX_GW_MESSAGE_RECEIVER ON GW_MESSAGE(RECEIVER_ID, READ_AT, CREATED_AT DESC);

-- 14. 근로계약
CREATE TABLE GW_CONTRACT_TEMPLATE (
    TEMPLATE_ID       BIGSERIAL PRIMARY KEY,
    TEMPLATE_NM       VARCHAR(100) NOT NULL,
    CONTRACT_TYPE_CD  VARCHAR(20) NOT NULL,
    BODY_HTML         TEXT NOT NULL,
    DEFAULT_TERMS_JSON TEXT,
    USE_YN            CHAR(1) NOT NULL DEFAULT 'Y',
    CREATED_AT        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE GW_EMPLOYMENT_CONTRACT (
    CONTRACT_ID            BIGSERIAL PRIMARY KEY,
    CONTRACT_NO            VARCHAR(50) NOT NULL,
    USER_ID                BIGINT NOT NULL,
    TEMPLATE_ID            BIGINT,
    CONTRACT_TYPE_CD       VARCHAR(20) NOT NULL,
    START_DT               DATE NOT NULL,
    END_DT                 DATE,
    WORKPLACE              VARCHAR(200),
    JOB_DESCRIPTION        VARCHAR(500),
    WORK_HOURS_PER_WEEK    NUMERIC(4,1) NOT NULL DEFAULT 40,
    WORK_START_TIME        VARCHAR(10),
    WORK_END_TIME          VARCHAR(10),
    BREAK_MINUTES          INT NOT NULL DEFAULT 60,
    WEEKLY_HOLIDAY         VARCHAR(50),
    ANNUAL_PAID_LEAVE_DAYS INT NOT NULL DEFAULT 15,
    PROBATION_MONTHS       INT NOT NULL DEFAULT 0,
    SALARY_CONTRACT_ID     BIGINT,
    INSURANCE_APPLIED_JSON TEXT,
    SPECIAL_TERMS          TEXT,
    STATUS_CD              VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    ATTACH_GROUP_ID        BIGINT,
    COMPANY_SIGNED_AT      TIMESTAMP,
    EMPLOYEE_SIGNED_AT     TIMESTAMP,
    EMPLOYEE_SIGNATURE     TEXT,
    TERMINATION_DT         DATE,
    TERMINATION_REASON     VARCHAR(500),
    CREATED_AT             TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY             BIGINT,
    UPDATED_AT             TIMESTAMP
);
CREATE UNIQUE INDEX UX_GW_EMP_CONTRACT_NO ON GW_EMPLOYMENT_CONTRACT(CONTRACT_NO);
CREATE INDEX IX_GW_EMP_CONTRACT_USER ON GW_EMPLOYMENT_CONTRACT(USER_ID, START_DT DESC);

-- 15. 사업자 계약 / 대금 관리
CREATE TABLE GW_VENDOR (
    VENDOR_ID      BIGSERIAL PRIMARY KEY,
    VENDOR_TYPE_CD VARCHAR(20) NOT NULL,
    BIZ_NO         VARCHAR(20) NOT NULL,
    COMPANY_NM     VARCHAR(150) NOT NULL,
    CEO_NM         VARCHAR(50),
    BIZ_KIND       VARCHAR(100),
    BIZ_ITEM       VARCHAR(200),
    ADDRESS        VARCHAR(300),
    ZIPCODE        VARCHAR(10),
    CONTACT_NM     VARCHAR(50),
    CONTACT_PHONE  VARCHAR(30),
    CONTACT_EMAIL  VARCHAR(150),
    BANK_CD        VARCHAR(10),
    BANK_ACCOUNT   VARCHAR(50),
    BANK_HOLDER    VARCHAR(100),
    TAX_TYPE_CD    VARCHAR(20) NOT NULL DEFAULT 'GENERAL',
    MEMO           VARCHAR(1000),
    USE_YN         CHAR(1) NOT NULL DEFAULT 'Y',
    CREATED_AT     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY     BIGINT,
    UPDATED_AT     TIMESTAMP,
    DELETED_AT     TIMESTAMP
);
CREATE UNIQUE INDEX UX_GW_VENDOR_BIZNO ON GW_VENDOR(BIZ_NO);
CREATE INDEX IX_GW_VENDOR_NM ON GW_VENDOR(COMPANY_NM);

CREATE TABLE GW_BIZ_CONTRACT (
    BIZ_CONTRACT_ID       BIGSERIAL PRIMARY KEY,
    CONTRACT_NO           VARCHAR(50) NOT NULL,
    VENDOR_ID             BIGINT NOT NULL,
    CONTRACT_TYPE_CD      VARCHAR(20) NOT NULL,
    TITLE                 VARCHAR(200) NOT NULL,
    START_DT              DATE NOT NULL,
    END_DT                DATE,
    AUTO_RENEW_YN         CHAR(1) NOT NULL DEFAULT 'N',
    RENEW_NOTICE_DAYS     INT NOT NULL DEFAULT 30,
    AMOUNT_NET            NUMERIC(16,0) NOT NULL DEFAULT 0,
    VAT_AMOUNT            NUMERIC(16,0) NOT NULL DEFAULT 0,
    AMOUNT_TOTAL          NUMERIC(16,0) NOT NULL DEFAULT 0,
    VAT_INCLUDED_YN       CHAR(1) NOT NULL DEFAULT 'N',
    CURRENCY_CD           VARCHAR(5) NOT NULL DEFAULT 'KRW',
    PAYMENT_TERMS_CD      VARCHAR(20) NOT NULL DEFAULT 'LUMPSUM',
    PAYMENT_DAY_OF_MONTH  INT,
    OWNER_USER_ID         BIGINT,
    DEPT_ID               BIGINT,
    STATUS_CD             VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    APPROVAL_DOC_ID       BIGINT,
    ATTACH_GROUP_ID       BIGINT,
    MEMO                  VARCHAR(2000),
    SIGNED_AT             TIMESTAMP,
    TERMINATED_AT         TIMESTAMP,
    TERMINATION_REASON    VARCHAR(500),
    CREATED_AT            TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY            BIGINT,
    UPDATED_AT            TIMESTAMP,
    DELETED_AT            TIMESTAMP
);
CREATE UNIQUE INDEX UX_GW_BIZ_CONTRACT_NO ON GW_BIZ_CONTRACT(CONTRACT_NO);
CREATE INDEX IX_GW_BIZ_CONTRACT_VENDOR ON GW_BIZ_CONTRACT(VENDOR_ID, START_DT DESC);
CREATE INDEX IX_GW_BIZ_CONTRACT_STATUS ON GW_BIZ_CONTRACT(STATUS_CD, END_DT);

CREATE TABLE GW_BILLING_SCHEDULE (
    SCHEDULE_ID      BIGSERIAL PRIMARY KEY,
    BIZ_CONTRACT_ID  BIGINT NOT NULL,
    SEQ_NO           INT NOT NULL,
    DUE_DT           DATE NOT NULL,
    AMOUNT_NET       NUMERIC(16,0) NOT NULL DEFAULT 0,
    VAT_AMOUNT       NUMERIC(16,0) NOT NULL DEFAULT 0,
    AMOUNT_TOTAL     NUMERIC(16,0) NOT NULL DEFAULT 0,
    MEMO             VARCHAR(255),
    STATUS_CD        VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    INVOICE_ID       BIGINT,
    CREATED_AT       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IX_GW_BILLING_CONTRACT ON GW_BILLING_SCHEDULE(BIZ_CONTRACT_ID, SEQ_NO);

CREATE TABLE GW_INVOICE (
    INVOICE_ID       BIGSERIAL PRIMARY KEY,
    INVOICE_NO       VARCHAR(50) NOT NULL,
    DIRECTION_CD     VARCHAR(10) NOT NULL,
    VENDOR_ID        BIGINT NOT NULL,
    BIZ_CONTRACT_ID  BIGINT,
    SCHEDULE_ID      BIGINT,
    ISSUE_DT         DATE NOT NULL,
    DUE_DT           DATE,
    AMOUNT_NET       NUMERIC(16,0) NOT NULL DEFAULT 0,
    VAT_AMOUNT       NUMERIC(16,0) NOT NULL DEFAULT 0,
    AMOUNT_TOTAL     NUMERIC(16,0) NOT NULL DEFAULT 0,
    PAID_AMOUNT      NUMERIC(16,0) NOT NULL DEFAULT 0,
    REMAINING_AMOUNT NUMERIC(16,0) NOT NULL DEFAULT 0,
    TAX_INVOICE_YN   CHAR(1) NOT NULL DEFAULT 'N',
    STATUS_CD        VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    OWNER_USER_ID    BIGINT,
    MEMO             VARCHAR(1000),
    ATTACH_GROUP_ID  BIGINT,
    CREATED_AT       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY       BIGINT,
    UPDATED_AT       TIMESTAMP,
    DELETED_AT       TIMESTAMP
);
CREATE UNIQUE INDEX UX_GW_INVOICE_NO ON GW_INVOICE(INVOICE_NO);
CREATE INDEX IX_GW_INVOICE_VENDOR ON GW_INVOICE(VENDOR_ID, ISSUE_DT DESC);
CREATE INDEX IX_GW_INVOICE_STATUS_DUE ON GW_INVOICE(STATUS_CD, DUE_DT);

CREATE TABLE GW_TAX_INVOICE (
    TI_ID             BIGSERIAL PRIMARY KEY,
    INVOICE_ID        BIGINT NOT NULL,
    TI_NO             VARCHAR(50),
    TI_TYPE_CD        VARCHAR(20) NOT NULL DEFAULT 'ELECTRONIC',
    DIRECTION_CD      VARCHAR(10) NOT NULL,
    ISSUE_DT          DATE NOT NULL,
    SUPPLIER_BIZ_NO   VARCHAR(20),
    BUYER_BIZ_NO      VARCHAR(20),
    ITEM_NM           VARCHAR(200),
    AMOUNT_NET        NUMERIC(16,0) NOT NULL DEFAULT 0,
    VAT_AMOUNT        NUMERIC(16,0) NOT NULL DEFAULT 0,
    AMOUNT_TOTAL      NUMERIC(16,0) NOT NULL DEFAULT 0,
    APPROVAL_NO       VARCHAR(50),
    NTS_STATUS_CD     VARCHAR(20) NOT NULL DEFAULT 'NONE',
    ATTACH_GROUP_ID   BIGINT,
    MEMO              VARCHAR(500),
    CREATED_AT        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IX_GW_TAX_INVOICE ON GW_TAX_INVOICE(INVOICE_ID);

CREATE TABLE GW_PAYMENT (
    PAYMENT_ID       BIGSERIAL PRIMARY KEY,
    INVOICE_ID       BIGINT,
    PAY_TYPE_CD      VARCHAR(20) NOT NULL,
    PAY_DT           DATE NOT NULL,
    AMOUNT           NUMERIC(16,0) NOT NULL,
    METHOD_CD        VARCHAR(20) NOT NULL DEFAULT 'BANK_TRANSFER',
    BANK_CD          VARCHAR(10),
    BANK_ACCOUNT     VARCHAR(50),
    COUNTERPART_NM   VARCHAR(150),
    MEMO             VARCHAR(500),
    APPROVAL_DOC_ID  BIGINT,
    REG_USER_ID      BIGINT,
    CREATED_AT       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IX_GW_PAYMENT_INVOICE ON GW_PAYMENT(INVOICE_ID, PAY_DT DESC);

-- 16. 계정과목 / 부서예산 / 지출결의
CREATE TABLE GW_ACCOUNT_CODE (
    ACCOUNT_CD        VARCHAR(20) PRIMARY KEY,
    ACCOUNT_NM        VARCHAR(100) NOT NULL,
    PARENT_CD         VARCHAR(20),
    TYPE_CD           VARCHAR(20) NOT NULL DEFAULT 'EXPENSE',
    BUDGET_CONTROL_YN CHAR(1) NOT NULL DEFAULT 'N',
    NOTE              VARCHAR(255),
    USE_YN            CHAR(1) NOT NULL DEFAULT 'Y'
);

CREATE TABLE GW_DEPT_BUDGET (
    BUDGET_ID      BIGSERIAL PRIMARY KEY,
    DEPT_ID        BIGINT NOT NULL,
    ACCOUNT_CD     VARCHAR(20) NOT NULL,
    BUDGET_YEAR    INT NOT NULL,
    BUDGET_MONTH   INT NOT NULL,
    BUDGET_AMOUNT  NUMERIC(14,0) NOT NULL DEFAULT 0,
    USED_AMOUNT    NUMERIC(14,0) NOT NULL DEFAULT 0
);
CREATE UNIQUE INDEX UX_GW_DEPT_BUDGET ON GW_DEPT_BUDGET(DEPT_ID, ACCOUNT_CD, BUDGET_YEAR, BUDGET_MONTH);

CREATE TABLE GW_EXPENSE_REPORT (
    REPORT_ID            BIGSERIAL PRIMARY KEY,
    REPORT_NO            VARCHAR(50) NOT NULL,
    DRAFTER_ID           BIGINT NOT NULL,
    DEPT_ID              BIGINT,
    TITLE                VARCHAR(200) NOT NULL,
    PURPOSE              VARCHAR(500),
    TOTAL_NET            NUMERIC(14,0) NOT NULL DEFAULT 0,
    TOTAL_VAT            NUMERIC(14,0) NOT NULL DEFAULT 0,
    TOTAL_AMOUNT         NUMERIC(14,0) NOT NULL DEFAULT 0,
    STATUS_CD            VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    APPROVAL_DOC_ID      BIGINT,
    REIMBURSE_REQUIRED_YN CHAR(1) NOT NULL DEFAULT 'N',
    REIMBURSE_PAYMENT_ID BIGINT,
    REIMBURSED_AT        TIMESTAMP,
    MEMO                 VARCHAR(1000),
    ATTACH_GROUP_ID      BIGINT,
    CREATED_AT           TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY           BIGINT,
    UPDATED_AT           TIMESTAMP,
    DELETED_AT           TIMESTAMP
);
CREATE UNIQUE INDEX UX_GW_EXP_REPORT_NO ON GW_EXPENSE_REPORT(REPORT_NO);
CREATE INDEX IX_GW_EXP_REPORT_DRAFTER ON GW_EXPENSE_REPORT(DRAFTER_ID, CREATED_AT DESC);
CREATE INDEX IX_GW_EXP_REPORT_STATUS ON GW_EXPENSE_REPORT(STATUS_CD);

CREATE TABLE GW_EXPENSE_ITEM (
    ITEM_ID            BIGSERIAL PRIMARY KEY,
    REPORT_ID          BIGINT NOT NULL,
    SEQ_NO             INT NOT NULL,
    EXPENSE_DT         DATE NOT NULL,
    CATEGORY_CD        VARCHAR(30) NOT NULL,
    ACCOUNT_CD         VARCHAR(20),
    VENDOR_NM          VARCHAR(200),
    VENDOR_BIZ_NO      VARCHAR(20),
    LINKED_VENDOR_ID   BIGINT,
    NET_AMOUNT         NUMERIC(14,0) NOT NULL DEFAULT 0,
    VAT_AMOUNT         NUMERIC(14,0) NOT NULL DEFAULT 0,
    TOTAL_AMOUNT       NUMERIC(14,0) NOT NULL DEFAULT 0,
    PAYMENT_METHOD_CD  VARCHAR(20) NOT NULL,
    CARD_LAST4         VARCHAR(4),
    RECEIPT_TYPE_CD    VARCHAR(20) NOT NULL DEFAULT 'CARD',
    LINKED_INVOICE_ID  BIGINT,
    PROJECT_CD         VARCHAR(30),
    MEMO               VARCHAR(500),
    ATTACH_GROUP_ID    BIGINT
);
CREATE INDEX IX_GW_EXP_ITEM_REPORT ON GW_EXPENSE_ITEM(REPORT_ID, SEQ_NO);
CREATE INDEX IX_GW_EXP_ITEM_ACCOUNT ON GW_EXPENSE_ITEM(ACCOUNT_CD, EXPENSE_DT);

-- 17. 메일 인프라
CREATE TABLE GW_MAIL_TEMPLATE (
    TEMPLATE_ID       BIGSERIAL PRIMARY KEY,
    TEMPLATE_CD       VARCHAR(50) NOT NULL,
    TEMPLATE_NM       VARCHAR(100) NOT NULL,
    SUBJECT           VARCHAR(200) NOT NULL,
    BODY_HTML         TEXT NOT NULL,
    ATTACH_TYPE_CD    VARCHAR(20) NOT NULL DEFAULT 'NONE',
    USE_YN            CHAR(1) NOT NULL DEFAULT 'Y',
    CREATED_AT        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT        TIMESTAMP
);
CREATE UNIQUE INDEX UX_GW_MAIL_TEMPLATE_CD ON GW_MAIL_TEMPLATE(TEMPLATE_CD);

CREATE TABLE GW_MAIL_LOG (
    MAIL_ID           BIGSERIAL PRIMARY KEY,
    TO_EMAIL          VARCHAR(500) NOT NULL,
    CC_EMAIL          VARCHAR(500),
    BCC_EMAIL         VARCHAR(500),
    SUBJECT           VARCHAR(300) NOT NULL,
    BODY_PREVIEW      VARCHAR(500),
    TEMPLATE_CD       VARCHAR(50),
    ATTACH_INFO_JSON  TEXT,
    RELATED_ENTITY    VARCHAR(50),
    RELATED_ID        VARCHAR(100),
    STATUS_CD         VARCHAR(20) NOT NULL DEFAULT 'QUEUED',
    QUEUED_AT         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    SENT_AT           TIMESTAMP,
    ERROR_MESSAGE     VARCHAR(2000),
    RETRY_CNT         INT NOT NULL DEFAULT 0
);
CREATE INDEX IX_GW_MAIL_LOG_STATUS ON GW_MAIL_LOG(STATUS_CD, QUEUED_AT);
CREATE INDEX IX_GW_MAIL_LOG_RELATED ON GW_MAIL_LOG(RELATED_ENTITY, RELATED_ID);
CREATE INDEX IX_GW_MAIL_LOG_TO ON GW_MAIL_LOG(TO_EMAIL, SENT_AT DESC);
